# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-r1uK6Hdryg-rE0CEe5HXqVl9A98QFQG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("netflix_titles.csv")
df.head()
df.info()
df.tail()

print(df.isnull().sum())

df.dropna(subset = ['director','country'],inplace = True)

df['date_added'] = pd.to_datetime(df['date_added'],errors = 'coerce')
df['year_added'] = df['date_added'].dt.year
df['year_added'].fillna(0,inplace = True )

df['type'].value_counts().plot(kind='bar',title = "Total Movies vs TV shows ")

df['country'].value_counts().head(10).plot(kind='barh',title = 'Top 10 countries by content')

df['year_added'].value_counts().sort_index().plot(kind='line',title = 'content added over the years')

df['listed_in'].str.split(',',expand = True ).stack().value_counts().head(10).plot(kind='bar',title = 'Most common genres')

df['director'].value_counts().head(3).plot(kind='bar',title = 'Top 3 directors ')

